name = "SolePostHoc"
uuid = "cf1aa0c3-12c9-4ebe-9bdc-bd6c2ca79b72"
authors = ["Eduard I. STAN", "Giovanni PAGLIARINI"]
version = "0.1.0"

[deps]
Metrics = "cb9f3049-315b-4f05-b90c-a8adaec4da78"
SoleBase = "142d03a6-36c4-4bac-9273-c7ed2abbbb4d"
SoleFeatures = "3ceb4e54-d968-4e97-8c18-2deeb0d429fb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
